final List<String> teamNames = [
  "Deutschland",
  "Frankreich",
  "England",
  "Spanien",
  "Italien",
  "Belgien",
  "Niederlande",
  "Portugal",
  "Polen",
  "Schweden",
  "Norwegen",
  "Dänemark",
  "Österreich",
  "Schweiz",
  "Tschechien",
  "Ungarn"
];

final List<String> locations = [
  "Berlin, DE",
  "Paris, FR",
  "London, UK",
  "Madrid, ES",
  "Rome, IT",
  "Brussels, BE",
  "Amsterdam, NL",
  "Lisbon, PT",
  "Warsaw, PL",
  "Stockholm, SE",
  "Oslo, NO",
  "Copenhagen, DK",
  "Vienna, AT",
  "Bern, CH",
  "Prague, CZ",
  "Budapest, HU"
];

final List<String> playerNames = [
  "Thomas Müller",
  "Manuel Neuer",
  "Leon Goretzka",
  "Joshua Kimmich",
  "Jamal Musiala",
  "Serge Gnabry",
  "Leroy Sané",
  "Antonio Rüdiger",
  "Niklas Süle",
  "Kai Havertz",
  "Timo Werner",
  "Ilkay Gündogan",
  "Kevin De Bruyne",
  "Romelu Lukaku",
  "Eden Hazard",
  "Thibaut Courtois",
  "Vinícius Júnior",
  "Lionel Messi",
  "Kylian Mbappé",
  "Neymar",
  "Cristiano Ronaldo",
  "Harry Kane",
  "Luka Modrić",
  "Robert Lewandowski",
  "Zlatan Ibrahimović",
  "Gianluigi Donnarumma",
  "Virgil van Dijk",
  "Memphis Depay"
];
